# Generated by Django 5.0.8 on 2024-08-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0002_dcocumento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dcocumento',
            new_name='Documento',
        ),
    ]
